### ISSUE TITLE
Permitir projeto rodar dentro do Docker

### ISSUE THREAD

**Issue by renatobmps** [renatobmps/hangman#14]
Adicionar `Dockerfile`:

```YAML
FROM node:21-slim as BUILDER 
LABEL maintainer="Renato Brandão"

WORKDIR /usr/app

COPY package*.json ./
RUN npm install

COPY src ./src
RUN npm run build

FROM node:21-alpine

ARG NODE_ENV

WORKDIR /usr/app

COPY --from=BUILDER /usr/app/ ./

EXPOSE 3000

CMD [ "npm", "start" ]
```

Criar arquivo `.dockerignore`:

```YAML
.github
.next
node_modules
```

Criar docker-compose.yml:

```YAML
version: '3'

services:
  app:
    container_name: hangman
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
```

Adicionar script no `package.json`:

```JSON
{
  "scripts": {
    "docker": "docker build -t hangman:latest .",
  }
}
```
