### ISSUE TITLE
Criar banco de dados via docker

### ISSUE THREAD

**Issue by renatobmps** [renatobmps/hangman#16]
Adicionar configuração do compose para iniciar banco de dados:

```yaml
services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
```

Adicionar também scripts no `package.json`:

```json
{
  "scripts": {
    "infra:up": "docker compose up",
    "infra:up:detach": "docker compose up -d",
    "infra:stop": "docker compose stop",
    "infra:down": "docker compose down",
    "infra:db:up": "docker compose up database",
    "infra:db:up:detach": "docker compose up -d database",
    "infra:db:stop": "docker compose stop database",
    "infra:db:down": "docker compose down database",
  }
}
```
